### ISSUE TITLE
TLP does not require `pm-utils`, should work with `openrc` + `udev`.

### ISSUE THREAD

**Issue by divoxx** [dywisor/tlp-portage#17]
Hey there.

Recently, I switched to `elogind` which requires `pm-utils` to be uninstalled and I noticed the `tlp` ebuild requires either `pm-utils` or `systemd`. 

According to TLP maintainer, `pm-utils` is not required and should work without systemd as long as udev is present. See https://github.com/linrunner/TLP/issues/363#issuecomment-421924385

I'm not sure if that's just an ebuild change of dropping `pm-utils` or if it will require more work but I'm happy to create a PR if you're willing to provide guidance.

**Comment by dywisor** [comment]
* affects non-systemd systems (OpenRC et al)

---

pm-utils is only used in the non-systemd case, for running TLP's [suspend/resume hooks](https://github.com/linrunner/TLP/blob/10279a60d3ccafee1d23d73de96ce40bfe7a5504/tlp.in#L256-L278) which tune pm settings for _faster_ suspend/resume and save/restore the rfkill state of bluetooth & wwan.

Possible options include:
1. use a different system suspend/resume trigger for running the relevant code - how do you suspend your system?
2. ditch this feature
3. keep pm-utils
4. a mix of the above, controlled with USE flags. For example, change the pm-utils flag so that it installs the necessary pm-utils scripts, but otherwise does nothing. This would allow to use systemd or a custom solution (or option 2.) if the flag is disabled.

**Comment by linrunner** [comment]
`@André:` please note that I just removed all pm-utils scripts from TLP master  

* https://github.com/linrunner/TLP/commit/c52de4750fab85e0a8db5dca9ed7694671f3547b
* https://github.com/linrunner/TLP/issues/363

It is quite simple to call 

    tlp suspend
    tlp resume

but I'm not yet aware of a replacement for pm-utils in this respect. Maybe you carry my old scripts in your ebuild until you find an alternative for pm-utils.

**Comment by divoxx** [comment]
@dywisor `elogind` controls resume/suspend which is extracted from systemd, which supports the same style of hooks as systemd.

If you place scripts on `/lib/elogind/system-sleep`, they should run before and after sleeping. I haven't tested it myself but the implementation does seen to point towards that:

* Defines `SYSTEM_SLEEP_PATH`: https://github.com/elogind/elogind/blob/f471150b6967ab218095d849ebb9cec96330cf42/meson.build#L176 and https://github.com/elogind/elogind/blob/f471150b6967ab218095d849ebb9cec96330cf42/meson.build#L262
* Then, defines `dirs` to include `SYSTEM_SLEEP_PATH`: https://github.com/elogind/elogind/blob/9d814db96b6f093fc334f60fa7c97fb3ce9852a8/src/sleep/sleep.c#L159-L162
* Calls the execution of the directory at https://github.com/elogind/elogind/blob/9d814db96b6f093fc334f60fa7c97fb3ce9852a8/src/sleep/sleep.c#L183 (pre) and https://github.com/elogind/elogind/blob/9d814db96b6f093fc334f60fa7c97fb3ce9852a8/src/sleep/sleep.c#L199-L200 (post).

With that, it should be possible to support `elogind` as an alternative to `pm-utils` and `systemd`.

**Comment by dywisor** [comment]
I've pushed an updated `tlp-9999-r2` ebuild, which installs `/lib/elogind/system-sleep/49-tlp-sleep` for handling suspend/resume. It resides in the [elogind](/dywisor/tlp-portage/tree/elogind) branch for now since it doesn't include any pm-utils functionality which I'd like to keep as an option for backwards compatbility.

Please test and verify with [trace mode](https://linrunner.de/en/tlp/docs/tlp-configuration.html#tracemode) that suspend/resume works as expected.

**Comment by linrunner** [comment]
I think i'll add this upstream when the test is sucessful ...

**Comment by dywisor** [comment]
@divoxx Any news? Don't hesitate to ask if you need further assistance.

**Comment by divoxx** [comment]
@dywisor sorry for the long delay on this. At the time I reported this, I uninstalled TLP and installed laptop mode as a temporary solution. I've been trying to find a good time to go back to TLP and test this but work has been busy and I never got around to doing it.

I'll try to find a time over the next week.

**Comment by linrunner** [comment]
Just added the elogind plumbing to TLP: https://github.com/linrunner/TLP/commit/366bb484aa5f139401c04940a9e337fa0b615464

**Comment by dywisor** [comment]
Great ;-)

I'll keep this issue open until I've updated the ``-9999`` ebuild in the maint branch.

**Comment by dywisor** [comment]
Hi everyone,

I gave this some thought and decided not to keep pm-utils functionality:

- support for pm-utils has been removed upstream (linrunner/TLP@c52de4750fab85e0a8db5dca9ed7694671f3547b)
- pm-utils itself seems to be pretty much unmaintained with bugs getting closed as wontfix, which makes it
difficult for me to justify putting any effort into it
- Two more modern alternatives exist, ``systemd's logind`` and its standalone variant ``elogind``. While they both might be considered too *heavy* by some, I'd expect that most notebook/desktop systems fullfil this requirement.
- Without ``systemd`` / ``elogind``, you'd lose suspend/resume logic, which may or may not affect your particular setup (hardware quirks during suspend/resume due to pm features, ...). This is unsupported by upstream TLP, so the upcoming `-9999` ebuild in the maint branch will suggest but not enforce ``systemd``/``elogind``.

**Comment by mid-kid** [comment]
Can't the pm-utils hook script be installed through a USE flag for pm-utils? It's a rather small script in which very little can go wrong (it requires next to no maintenance/support), and will help people whom are still using it.
I'd also like to point out that consolekit is still the default in Gentoo (17.0, at least), and installing elogind requires replacing it and reconfiguring everything that depends on it, whereas pm-utils works fine in tandem with it. Also, xfce4-power-manager requires pm_utils for whatever reason.

**Comment by divoxx** [comment]
I'm finally circling back to this, sorry for the huge delay but it was hard to find the time.

@dywisor I see that `9999-r2` only exists on the elogind branch, which doesn't appear in my overlay when I sync. What's a good way to test this?

**Comment by divoxx** [comment]
@dywisor ~I realized that since the elogind changes are on TLP 1.1, I was going to try installing that. It doesn't work though because the ebuild has a hard dependency on `systemd` and doesn't expose the `elogind` (nor removes the `pm-utils`) use flags.~

EDIT: Actually, I was mistaken about TLP 1.1 including the elogind changes.

**Comment by dywisor** [comment]
I've just pushed ``tlp-9999-r2`` with support for elogind to the maint branch.

@mid-kid Apparently I was just waiting for someone to speak up for pm-utils ;-) As you've suggested, I've added the necessary files to the overlay, which can be installed USE=pm-utils (disabled by default). However, this is more or less unsupported and likely to be removed should it cause me too many headaches in the future.

**Comment by linrunner** [comment]
Just curious: is there *really* something left in Gentoo calling pm-suspend?

**Comment by dywisor** [comment]
pm-utils will eventually vanish - [Gentoo Bug #659616](https://bugs.gentoo.org/659616).
Currently, a few packages keep it as an option. For xfce4-power-manager, it's a hard dep.

```
$ equery depends --all sys-power/pm-utils
 * These packages depend on sys-power/pm-utils:
kde-plasma/plasma-meta-5.14.5 (pm-utils ? sys-power/pm-utils)
kde-plasma/plasma-meta-5.15.1 (pm-utils ? sys-power/pm-utils)
net-misc/wicd-1.7.4-r3 (pm-utils ? sys-power/pm-utils)
sys-apps/razercfg-0.39-r1 (pm-utils ? sys-power/pm-utils)
sys-auth/consolekit-1.1.0-r1 (pm-utils ? sys-power/pm-utils)
sys-auth/consolekit-1.1.2 (pm-utils ? sys-power/pm-utils)
sys-auth/consolekit-1.2.0 (pm-utils ? sys-power/pm-utils)
sys-auth/consolekit-1.2.1 (pm-utils ? sys-power/pm-utils)
sys-auth/consolekit-9999 (pm-utils ? sys-power/pm-utils)
sys-power/powermgmt-base-1.31 (pm-utils ? >=sys-power/pm-utils-1.4.1)
xfce-base/xfce4-session-4.12.1-r1 (upower ? sys-power/pm-utils)
xfce-base/xfce4-session-4.12.1-r2 (upower ? sys-power/pm-utils)
xfce-extra/xfce4-power-manager-1.6.1 (sys-power/pm-utils)
```
