### ISSUE TITLE
tlp.service for systemd is missing

### ISSUE THREAD

**Issue by AxelG-DE** [dywisor/tlp-portage#28]
I hope I am not foolishly mistaken. I have just re-installed from the overlay. Documentation even talks about tlp.service, however, that file is not in the package.

equery files tlp also does not show this....

**Comment by dywisor** [comment]
With ``USE=pm-utils``, this is expected behavior as you would end up installing competing "on-power-source-change" mechanisms otherwise. Note that support for this USE flag is very limited (see #17).

With ``USE=-pm-utils``, this would be a bug. If so, please post the output of
```
emerge --info app-laptop/tlp
```
(interesting data: package version, repo, effective USE flags, ``INSTALL_MASK``)

**Comment by AxelG-DE** [comment]
Understood. 
I changed to USE=-pm-utils and tlp.service poped up! 
TNX

**Comment by linrunner** [comment]
@dywisor : why don't you just remove the pm-utils switch? pm-utils is unmaintained for many years, TLP doesn't support it anymore and it seems to be just an annoyance for users.

**Comment by dywisor** [comment]
With the next release, I suppose. In June, pm-utils will be unmaintained for 10 years.

It is unfortunate that no other lightweight alternative exist (*) - (e)logind requires D-Bus and whatnot, but that does not justify keeping dead weight forever.

(*) unverified claim based on what upstream supports and a quick peek at packages available in the ``sys-power`` category

Regarding the issue at hand, the pm-utils route in the package is an optional feature that has to be explicitly enabled by admins at package build time, the docs discourage doing so.

**Comment by AxelG-DE** [comment]
> Regarding the issue at hand, the pm-utils route in the package is an optional feature that has to be explicitly enabled by admins at package build time, the docs discourage doing so.

As you know, for Gentoo, there is no real package maintainer (just the ebuild maintainer) and users set their USE-variable often system wide in /etc/make.conf, regardless, what the ebuild pre-sets. That pm-utils is unmaintained, one does not notice, as long it just works, hence everything stays as it is :-)

Having said that, it is valid for taking that option off and keeping it in :)

**Comment by linrunner** [comment]
> as long it just works

I'm not so shure if this is still the case. In Debian, for example, _pm-utils_ has long been practically inert, because neither _upowerd_ invokes it upon change of power source nor is it invoked on suspend/resume – meaning that none of the hooks in **power.d/** and **sleep.d/** will ever get executed.

@dywisor : could you check if my assumption is true in Gentoo?

**Comment by linrunner** [comment]
Some evidence: 
* https://bugs.gentoo.org/596988
* https://bugs.gentoo.org/659616

**Comment by dywisor** [comment]
Relevant Gentoo bug tracker for ``pm-utils`` removal is [Gentoo Bug #659616](https://bugs.gentoo.org/659616).

With ``USE=pm-utils``, pm-utils is solely used for suspend/resume,
power source changes are handled by udev rules == as in upstream.

I really don't know whether pm sleep hooks still work.
It's safe to assume that they still get executed when ``pm-suspend`` is directly invoked to put the system in sleep state. That's the most common use case for ``USE=pm-utils``, I suppose: some lightweight display manager with a keyboard shortcut for ``pm-suspend``.
Anything beyond that is likely broken - apparently, xfce4-power-manager still supports ``pm-suspend``.

Maybe @mid-kid can comment on that. Do pm-utils sleep/resume hooks still work for ``app-laptop/tlp``? Should be visible in syslog with trace mode enabled (``TLP_DEBUG="run"`` should be sufficient).

**Comment by mid-kid** [comment]
I've used `pm-utils` until it was dropped from the default gentoo profile, since really, a lot of programs are dropping support for it.
Don't really feel like reinstalling it, since the switch to elogind wasn't completely smooth either, but I was using it in combination with `xfce4-power-manager` which I'm pretty sure [called upon consolekit2](https://github.com/xfce-mirror/xfce4-power-manager/blob/master/src/xfpm-power.c#L472) for power management if available (I used it), which in turn [tends to use `pm-suspend`](https://github.com/ConsoleKit2/ConsoleKit2/blob/master/tools/linux/ck-system-suspend).
So yeah, I think the hooks were still working, since IIRC the main reason I asked for the USE flag was because my laptop wouldn't suspend without the script :P

**Comment by dywisor** [comment]
Thanks for your feedback. Alright, I'll schedule ``pm-utils`` for the next release.
