### ISSUE TITLE
Depend on acpi_call

### ISSUE THREAD

**Issue by thorstent** [dywisor/tlp-portage#7]
To control thinkpad batteries it seems tpacpi needs acpi_call kernel module installed. I think tlp should depend on that for some use flag.

**Comment by dywisor** [comment]
You need to install it manually.

There's no sane way to specify optional (runtime) dependencies in ebuilds. The usual solution is to declare per-package/per-feature-set USE flags and/or to print the deps during installation.

The USE-flag approach is misuse as per [devmanual](http://devmanual.gentoo.org/general-concepts/use-flags/index.html). The `tlp_suggests` flag exists for convenience reasons and covers the most common optional deps, but acpi_call is hardware-specific, so I'd have to add another flag (and yet another for tp_smapi, not to think of possible future battery backends), which is why I list them in the [README](https://github.com/dywisor/tlp-portage#setup-instructions) instead.

If you want to have some sort of meta package that pulls in TLP + acpi_call, you may achieve this by means of a package set:

```
$ mkdir -p -- /etc/portage/sets

$ cat << EOF > /etc/portage/sets/tlp
app-laptop/tlp
#app-laptop/tp_smapi
app-laptop/acpi_call
EOF

$ emerge -au @tlp
```

**Comment by thorstent** [comment]
Hi, thanks for your reply.

I think the use flag tpacpi-bundled should pull in acpi_call. If you look at tpacpi-bat ebuild file in portage you will notice that it has acpi_call as a dependency. So it is a bit odd that if I install the bundled tpacpi it does not have the same dependencies as the standalone tpacpi (perl is another dependency). Further it seems that tpacpi does not function at all without acpi_call (I may be wrong though).

http://sources.gentoo.org/cgi-bin/viewvc.cgi/gentoo-x86/app-laptop/tpacpi-bat/tpacpi-bat-2.1.ebuild?view=markup

**Comment by dywisor** [comment]
> I think the use flag tpacpi-bundled should pull in acpi_call.

No, that'd add a hard dep on acpi_call.

> So it is a bit odd that if I install the bundled tpacpi it does not have the same dependencies as the standalone tpacpi (perl is another dependency). Further it seems that tpacpi does not function at all without acpi_call (I may be wrong though).

That's correct, but TLP does not aim to provide a system-wide tpacpi-bat and is able to handle absence of the acpi_call module, so acpi_call is really optional.

In case of `tpacpi-bundled`, TLP installs its bundled script to /usr/lib/tlp-pm/ and the dep on acpi_call is left open => no need to declare it as hard dep.

 `-tpacpi-bundled` allows to bring your own script (/usr/bin/tpacpi-bat). This file is provided by  `app-laptop/tpacpi-bat`, which depends on acpi_call. You wouldn't normally install this package if you didn't want to, so that's OK.

Edit:
Forgot to mention that `USE=-tpacpi-bundled` is really not the way to go unless you participate in tpacpi-bat development (i.e. install the -9999 live package and/or have custom patches). The bundled script is more recent than any of the release-versioned ebuilds, which has led to compatibility issues in the past.

**Comment by dywisor** [comment]
Closing as wontfix -- acpi_call remains an optional dependency listed in the README
